### ISSUE TITLE
nearest neighbor

### ISSUE THREAD

**Issue by mse0** [ehsanik/dogTorch#1]
Hi, 
I can't seem to figure out what you did for nearest neighbor for both acting and planning. For acting, the paper says it "uses the features obtained from a Resnet-18 network trained on imagenet." How is that used to predict 5 frames into the future? 

Likewise, for planning, nearest neighbor "concatenates the features obtained from resnet-18 trained on imagenet and searches for a plan of the required size that corresponds to the closest feature." If the plan is the sequence of actions in between the first and fifth image, how do you use the features from those images to get that?

I don't think this part was implemented in the code on github. 

Thanks!

**Comment by ehsanik** [comment]
We forgot to add the codes for these models. I just added them [here](https://github.com/ehsanik/dogTorch/blob/master/models/models_nearest_neighbor.py) and [here](https://github.com/ehsanik/dogTorch/blob/master/models/models_nearest_neighbor_planning.py). 

Thanks for pointing this out.
